### PR TITLE
fix invalid typespec

### PR DESCRIPTION
**Pull request by epinault**
See #660

### CODE REVIEW

**Review by btkostner — APPROVED** [review]

**Comment by epinault** [comment]
is it possible to get it merged?

**Comment by btkostner** [comment]
Sorry about that. Looks like CI is failing but it's unrelated to this change.

**Comment by epinault** [comment]
are you going to release a new version? or do you need a PR for that too?

**Comment by btkostner** [comment]
It will be released when we get everything from the org transfer setup (like hex auth.) Also when we get some other quick fixes in.

**Comment by epinault** [comment]
any timeline ? we have been waiting for that fix for a while

**Comment by btkostner** [comment]
There is not a timeline for a release, but in the mean time you can pull the code directly from GitHub by using this in your `mix.exs` file:

```ex
def deps do
  [
    {:bamboo, github: "beam-community/bamboo", ref: "7b5d99dd46b5466e5e4f857c2403a76114212e3e"}
  ]
end
```

**Pull request merged**
